import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';

import './globals.css';

import theme from '@/app/_utils/theme/theme';
import SessionWrapper from '@/components/SessionWrapper';

import { interceptorFunc } from './_utils/apiConfig/axiosConfig';
import StoreProvider from './redux/storeProvide';

const inter = Inter({ subsets: ['latin'] });

interceptorFunc();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <StoreProvider>
        <html lang='en'>
          <body className={inter.className}>
            <AppRouterCacheProvider>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </AppRouterCacheProvider>
          </body>
        </html>
      </StoreProvider>
    </SessionWrapper>
  );
}
